apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector: 
    app: nexus-server
  type: NodePort  
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32000
      name: http
    - port: 8082
      targetPort: 8082
      nodePort: 32001
      name: docker-repo